services:
  backend:
    build: .
    ports:
      - 34242:5000
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://appuser:qFq9TPj5GoNd9ftZ2fuSXexY1x1JqDlk@dpg-d4c2m5f5r7bs73a4qc6g-a/lecture14
    depends_on:
      - database
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "54242:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: